### ISSUE TITLE
Namespace issues

### ISSUE THREAD

**Issue by JesperKuipers** [shambik/NeweggScraper#2]
Had a few namespace issues but for others reading this it's easy to fix. 

Just do these 4 steps:
1. right click on Solution > Restore NuGet packages
2. right click on Solution > Clean Solution
3. right click on Solution > Build Solution
4. Close Visual Studio and re-open.

**Comment by shambik** [comment]
Not an issue, did not reproduce on a clean environment.

Need to build first then run
