### ISSUE TITLE
Seems like the program ignores if the loop checkbox is checked

### ISSUE THREAD

**Issue by JesperKuipers** [shambik/NeweggScraper#4]
Seems like the program ignores if the loop checkbox is checked
![image](https://user-images.githubusercontent.com/44586411/102907967-1344b900-4477-11eb-8e75-5c8c55b7ed4e.png)

**Comment by shambik** [comment]
No its probably a try catch some where i need to find it it still running
tho After u hit ok

It happens when u use discord notification?

Or it always happens whenever the checkboz is u checked?

בתאריך יום ג׳, 22 בדצמ׳ 2020, 18:00, מאת JesperKuipers ‏<
notifications@github.com>:

**Comment by JesperKuipers** [comment]
It happens every time I run it after the new update (discord added)

**Comment by shambik** [comment]
fixed
